### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by tyeeman** [RomanosTrechlis/blog-gen#1]
Greetings. I wanted to use local folder also and am trying to modify zupzup but see you have done it already. Nice, but how do I install yours? When I run ```go get github.com/RomanosTrechlis/blog-gen``` I get an error of no go files in your repo main folder?

**Comment by RomanosTrechlis** [comment]
Hi, sorry for not responding earlier.
You can use `go get -v github.com/RomanosTrechlis/blog-gen/cmd/blog-generator`.

**Comment by tyeeman** [comment]
Thanks
